### PR TITLE
Added explanation for disaster cycle and maturity on hover

### PR DESCRIPTION
**Pull request by Eyu-Tes**
I accidentally closed the previous PR, sorry.

To answer your previous question, both your issues are on the LIB. 
1. I was using an icon from emojipedia (for consistency). I would have to find another one.
2. The descriptions for the maturity level are on the LIB as well. We would have to publish a new version when it is modified.

### CODE REVIEW

**Comment by OzgeOzkaya** [comment]
Oki if you could find a more recognizable one, I would appreaciate it @Eyu-Tes Thank you for further collabration! It means a lot

**Comment by Eyu-Tes** [comment]
So do we have the explanations for the maturity levels?

**Comment by OzgeOzkaya** [comment]
We will get them on Monday :) If it is fine for you, let's postpone it on Monday

**Comment by Eyu-Tes** [comment]
That is totally fine.

**Comment by OzgeOzkaya** [comment]
@Eyu-Tes I actually realized that the information icon for the idea, validation, prototype and production looks fine. Can't we have the same appearance for the disaster phases. I guess they are the same but the phases icons are bold.

**Comment by Eyu-Tes** [comment]
Sure, we can. The description for the maturity levels will also be added inside the App.

**Comment by OzgeOzkaya** [comment]
@Eyu-Tes let me know when your dev is finalized :)

**Comment by Eyu-Tes** [comment]
I need to use the latest version of the LIB on the App. The last time I published the LIB on NPM there were some mistakes. I have to talk to Nuno about that.

**Pull request merged**
