### PR TITLE
Merged TechDrawer and FilterDrawer for responsiveness simplicity, cre…

### PR DESCRIPTION
**Pull request by vladislawa**
…ated Drawer for Mobile filters, added responsiveness to Radar page

### CODE REVIEW

**Comment by vladislawa** [comment]
@OzgeOzkaya I tried to make sure all the screen sizes are responsive and working, however please let me know if you notice any issues

**Comment by OzgeOzkaya** [comment]
Thanks @vladislawa !

I checked it on different devices with simulation and working great. I really appreciate the responsive screen size adaptation of the custom desktop browsers.

- What I realize is about the main apperance of the radar as %100(default) zoomed desktop browser:

rdr_resp

It seems like the radar got a bit smaller and the card location moved to left which made a recognizable gap between the "how to use" button and the card. Any chance for you to check it?

- Another comment is about tablet devices(ipad air etc), any possibility move card to bottom of radar for those devices? Not the most priority but if it is easy could you please check :)

**Comment by OzgeOzkaya** [comment]
+ the hover functionality doesn't work properly. just to add

**Comment by OzgeOzkaya** [comment]
@vladislawa thank you for fast response. Actually we don't need a hovering functionality on mobiles. What I realized is about the desktop browser hover functionality. It didn't work properly. It may cause from my side, could you please also check from your laptop/pc?

**Comment by vladislawa** [comment]
@OzgeOzkaya I fixed hover functionality (I think I accidentally broke it, sorry) - I am still however working on tablet responsiveness and fixing the grid

**Pull request merged**
