### PR TITLE
Fixes #198 

### LINKED ISSUE #198: [UI change] Fix the mobile radar view
- Fit the lines or centerize the quadrant radar
- Remove information tooltip from mobile view

### PR DESCRIPTION
**Pull request by jacksono**
Screenshot 2022-09-27 at 08 49 14

Screenshot 2022-09-27 at 09 01 04

### CODE REVIEW

**Comment by jacksono** [comment]
@OzgeOzkaya  For the quadrant views, I was not able to implement the colored radar because the text was not clickable and I did not find a way to make it clickable. The closest I got was to remove the radar colors and leave the circles.

I also tried to remove the inner circles but did not find a clean way to do it. What we are left with is this:

Screenshot 2022-09-27 at 09 01 04

**Comment by jacksono** [comment]
About removing the top and bottom spaces around the radar on mobile view. The radar is vertically centered depending on the screen height, Removing the top or bottom spaces may leave  an unwanted space between the bottom nav and the bottom of the screen - see screenshots.
Screenshot 2022-09-27 at 08 49 31

Screenshot 2022-09-27 at 09 34 39

**Comment by jacksono** [comment]
About removing the information tooltip on the mobile view, I took a look and from the Radar Lib repo and I noticed that those information tooltips do not exist on the master and develop branches. Is it possible that the current branch on production does not have the changes we have in develop/master on Radar_Lib ?
Screenshot 2022-09-27 at 09 40 06

**Comment by OzgeOzkaya** [comment]
Dear @jacksono thank you for the PR! I think the mobile radar view looks much better than before. For the information tooltips, I must ask this feature and the codes to the previous colleagues.

I will merge this PR for the new mobile radar layout and let you know about the information tooltips

**Pull request merged**
