### PR TITLE
Issue 172 main page icon fixes

### PR DESCRIPTION
**Pull request by haksuman**
- Upper-left UNDP icon now directing to UNDP's website for onClick event
- Left-navbar buttons now align with UNDP Icon's blue color
- Bottom-middle icons now directing to relevant websites for onClick event

### CODE REVIEW

**Comment by jacksono** [comment]
Hi @haksuman this looks good. I just want to point out that the website links do not seem to be working for the 767px breakpoint.

Screenshot 2022-08-25 at 09 40 03

**Comment by OzgeOzkaya** [comment]
Hi colleagues! @haksuman @jacksono 

Shall we put the logos as png on the background image instead of integrating the logos from the html/css. What do you think?

**Comment by jacksono** [comment]
> Hi colleagues! @haksuman @jacksono
> 
> Shall we put the logos as png on the background image instead of integrating the logos from the html/css. What do you think?

Hi @OzgeOzkaya for this case I do not think having the logos as `background image` is worth the change, yet it can play a semantic role if we keep it in the html.

Did you have a reason for the suggestion?

**Comment by haksuman** [comment]
This issue originates from mobile app view has different components as icons. However, now icons are clickable and directing to relevant urls with up to date pull request.

**Comment by haksuman** [comment]
This issue originates from mobile app view has different components as icons. However, now icons are clickable and directing to relevant urls with up to date pull request.

**Pull request merged**
