### PR TITLE
Move radar title to the top of the page.

### PR DESCRIPTION
**Pull request by jacksono**
The ‘Frontier Technology Radar for Disaster Risk Reduction (FTR4DRR) should be placed to the top of the page, at the same level as the ‘how to use’ and ‘filter’ buttons.

localhost_3000_

localhost_3000_ (1)

### CODE REVIEW

**Comment by OzgeOzkaya** [comment]
Hi @jacksono! 
Screenshot_110

The title is not fitting in the mobile version. Is it caused by the radar? Since it also needs responsiveness. If it will be fixed with the radar layout, I will merge this PR

**Comment by jacksono** [comment]
Hi @OzgeOzkaya , yes the  title on mobile is affected by the radar.
I am in the process of optimizing the mobile view s discussed:

Screenshot 2022-09-12 at 10 19 49

**Comment by OzgeOzkaya** [comment]
Sounds great! If you have another branch for the other tasks, I can merge this PR and delete the branch

**Comment by jacksono** [comment]
Yes, I am working on a separate branch for the responsiveness. -`issue183-radar-layout`

**Comment by OzgeOzkaya** [comment]
Thanks! Merging...

**Pull request merged**
