### PR TITLE
Improvement/datalists performance remove accordion

### PR DESCRIPTION
**Pull request by nmpribeiro**
Note: merge after PR#89

Speeds up the radar when we see the `Stage` component. For that, I profiled a the app and noticed that `Box` `Flex` and `Accordion` from `Chakra-UI` were taking too much time.

TODO: 

- [x] Filter by tech selected

### CODE REVIEW

**Comment by nmpribeiro** [comment]
@fpenarru wait 😅 we still need to filter by tech and double check how to make it better (by following the mockups)

**Comment by fpenarru** [comment]
@nmpribeiro Just tested it. I think it is clearly much faster, congrats!! :-)

**Comment by OzgeOzkaya** [comment]
@nmpribeiro if there is no objection, gonna merge :)

**Comment by nmpribeiro** [comment]
@OzgeOzkaya you can test and merge now

**Comment by fpenarru** [comment]
Hi @nmpribeiro 
I have incorporated the new HorizonItem, but I still have problems with slow behavior (after all, there are 4 more items).
Maybe we can try this component from MUI library: https://mui.com/material-ui/react-accordion/
Do you think it could be worthy to try it?
Best regards!

**Comment by nmpribeiro** [comment]
@fpenarru  It would be interesting to check the findings of such try out. If we prove MUI is superior in performance, then I am all in to switch the whole app to MUI.
What I would like to avoid is having multiple frameworks at the same time.

**Pull request merged**
